---
- job:
    name: barbican-tox-functional
    parent: devstack-tox-functional
    description: Functional testing
    required-projects:
      - name: openstack/barbican
      - name: openstack/castellan
      - name: openstack/openstacksdk
    vars:
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican
      tox_install_siblings: true

- job:
    name: barbican-dogtag-tox-functional
    nodeset: devstack-single-node-fedora-latest
    parent: barbican-tox-functional
    description: |
      Functional testing for DogTag backend
    vars:
      devstack_services:
        barbican-dogtag: true

- job:
    name: barbican-tox-functional-fips
    nodeset: devstack-single-node-centos-9-stream
    parent: barbican-tox-functional
    description: |
      Functional testing for a FIPS enabled Centos 8 system
    pre-run: playbooks/enable-fips.yaml
    vars:
      nslookup_target: 'opendev.org'

- job:
    name: barbican-vault-tox-functional
    parent: barbican-tox-functional
    description: |
      Functional testing for Hashicorp Vault backend
    vars:
      devstack_services:
        barbican-vault: true
      tox_environment:
        VAULT_PLUGIN_ENABLED: 1

- job:
    name: barbican-kmip-tox-functional
    parent: devstack-tox-functional
    description: |
      Functional testing for KMIP backend using PyKMIP
    vars:
      devstack_services:
        kmip: true

- job:
    name: barbican-tempest-plugin-simple-crypto-zed
    parent: barbican-tempest-plugin-simple-crypto
    nodeset: openstack-single-node-focal
    override-checkout: unmaintained/zed
    required-projects:
      - name: openstack/barbican-tempest-plugin
        override-checkout: zed-last
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            key_manager:
              min_microversion: '1.0'
              max_microversion: '1.1'

- job:
    name: barbican-tempest-plugin-simple-crypto-ipv6-only-zed
    parent: barbican-tempest-plugin-simple-crypto-ipv6-only
    nodeset: openstack-single-node-focal
    override-checkout: unmaintained/zed
    required-projects:
      - name: openstack/barbican-tempest-plugin
        override-checkout: a31f9ef3a68e58fe970783d1b7b4cff45e4ee78b
    vars:
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            key_manager:
              min_microversion: '1.0'
              max_microversion: '1.0'

- job:
    name: barbican-simple-crypto-devstack-tempest-castellan-from-git
    parent: barbican-tempest-plugin-simple-crypto-castellan-src
    description: |
      Compatibility alias for barbican-tempest-plugin-simple-crypto-castellan-src

- job:
    name: barbican-simple-crypto-devstack-tempest-cursive
    parent: barbican-tempest-plugin-simple-crypto-cursive
    description: |
      Compatibility alias for barbican-tempest-plugin-simple-crypto-cursive

- job:
    name: barbican-grenade
    parent: grenade
    required-projects:
      - opendev.org/openstack/grenade
      - opendev.org/openstack/barbican
      - name: opendev.org/openstack/barbican-tempest-plugin
        override-checkout: zed-last
      - opendev.org/openstack/python-barbicanclient
    vars:
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican
      devstack_services:
        barbican-svc: true
        barbican-retry: true
      tempest_plugins:
        - barbican-tempest-plugin
      tempest_test_regex: '\[.*\bsmoke\b.*\]|^(barbican_tempest_plugin.tests)'
      tox_envlist: all

- project:
    queue: barbican
    templates:
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - barbican-tox-functional
        - barbican-vault-tox-functional:
            voting: false
        - barbican-grenade:
            voting: false
        - barbican-tempest-plugin-simple-crypto-zed
        - barbican-tempest-plugin-simple-crypto-secure-rbac:
            voting: false
        - barbican-tempest-plugin-simple-crypto-ipv6-only-zed:
            voting: false
        - barbican-tox-functional-fips
        - octavia-v2-dsvm-tls-barbican
    gate:
      jobs:
        - barbican-tox-functional
    experimental:
      jobs:
        - barbican-dogtag-tox-functional
        - barbican-kmip-tox-functional

