"""add new columns type meta containerId

Revision ID: 1e86c18af2dd
Revises: 13d127569afa
Create Date: 2014-06-04 09:53:27.116054

"""

# revision identifiers, used by Alembic.
revision = '1e86c18af2dd'
down_revision = '13d127569afa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('container_id', sa.String(length=36), nullable=True))
    op.add_column('orders', sa.Column('meta', sa.Text, nullable=True))
    op.add_column('orders', sa.Column('type', sa.String(length=255), nullable=True))
    ### end Alembic commands ###
