"""add owning project and creator to CAs

Revision ID: 3c3b04040bfe
Revises: 156cd9933643
Create Date: 2015-09-04 12:22:22.745824

"""

# revision identifiers, used by Alembic.
revision = '3c3b04040bfe'
down_revision = '156cd9933643'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate_authorities',
                  sa.Column('creator_id', sa.String(length=255),
                                                    nullable=True))
    op.add_column('certificate_authorities',
                  sa.Column('project_id', sa.String(length=36),
                                                    nullable=True))
    op.create_foreign_key('cas_project_fk', 'certificate_authorities',
                          'projects', ['project_id'], ['id'])
    ### end Alembic commands ###
