"""bp/mime-type-revamp

Revision ID: b4ba6a2a663
Revises: 53c2ae2df15d
Create Date: 2013-07-26 15:25:44.193889

"""

# revision identifiers, used by Alembic.
revision = 'b4ba6a2a663'
down_revision = '53c2ae2df15d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encrypted_data', sa.Column('content_type',
                                              sa.String(length=255),
                                              nullable=True))
    op.alter_column('secrets', u'mime_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('orders', u'secret_mime_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('secrets', u'mime_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('orders', u'secret_mime_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.drop_column('encrypted_data', 'content_type')
    ### end Alembic commands ###
