"""add-cert-to-container-type

Revision ID: cd4106a1a0
Revises: 1e86c18af2dd
Create Date: 2014-06-10 15:07:25.084173

"""

# revision identifiers, used by Alembic.
revision = 'cd4106a1a0'
down_revision = '1e86c18af2dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute( 'ALTER TABLE containers CHANGE type type ENUM(\'generic\',\'rsa\',\'certificate\') DEFAULT NULL');
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute( 'ALTER TABLE containers CHANGE type type ENUM(\'generic\',\'rsa\') DEFAULT NULL');
    ### end Alembic commands ###
